version: "3.1"

services:
  db:
    image: mysql:latest
    container_name: phonebook-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=phonebook
    volumes:
      - /var/mysql:/var/lib/mysql
  api:
    image: phonebook-api:1.0
    container_name: phonebook-api
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 80:8080
